### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by seniorquico** [stackpath/virtual-kubelet-stackpath#21]
There is no license file, a link to a license, or even mention of the terms "license" or "licence" in this GitHub repository. It would be awesome if you included a LICENSE file (or similar) so that people understood the capacity that the source code in this repository may be used.

**Comment by rolikoff** [comment]
Thank you for bringing this to our attention, @seniorquico. I have initiated a pull request to include a LICENSE file in the repository. We have decided to adopt the Mozilla Public License Version 2.0 as the licensing terms for this project. Your feedback is greatly appreciated!
